[[navbar]]
  identifier = "about"
  name       = "आमच्याबद्दल"
  url        = "/mr/pages/about/"
  weight     = 1

[[navbar]]
  identifier = "blogs"
  name       = "ब्लॉग"
  url        = "/mr/posts/"
  weight     = 2

[[navbar]]
  identifier = "cat-security"
  name       = "सुरक्षा"
  url        = "/mr/tags/security/"
  weight     = 3

[[navbar]]
  identifier = "cat-ai"
  name       = "AI साधने"
  url        = "/mr/tags/ai-tools/"
  weight     = 4

[[navbar]]
  identifier = "cat-webdev"
  name       = "वेब डेव"
  url        = "/mr/tags/web-development/"
  weight     = 5

[[navbar]]
  identifier = "cat-frontend"
  name       = "फ्रंटएंड"
  url        = "/mr/tags/frontend/"
  parent     = "cat-webdev"
  weight     = 1

[[navbar]]
  identifier = "cat-javascript"
  name       = "JavaScript"
  url        = "/mr/tags/javascript/"
  parent     = "cat-webdev"
  weight     = 2

[[navbar]]
  identifier = "cat-css"
  name       = "CSS"
  url        = "/mr/tags/css/"
  parent     = "cat-webdev"
  weight     = 3

[[navbar]]
  identifier = "cat-networking"
  name       = "नेटवर्किंग"
  url        = "/mr/tags/networking/"
  weight     = 6

[[navbar]]
  identifier = "cat-systemdesign"
  name       = "सिस्टम डिझाइन"
  url        = "/mr/tags/system-design/"
  weight     = 7
